services:
  example-mysql:
    image: mysql:8.0.38-debian
    platform: linux/amd64  # ARM64 호환성을 위한 플랫폼 지정
    restart: always
    #    command: --lower_case_table_names=1
    container_name: mysql-for-jpa
    hostname: mysql-for-jpa
    ports:
      - "23306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=test1357
      - MYSQL_DATABASE=jpa_mysql
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1357
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/